- platform: template
  sensors:
    motion_gym:
      friendly_name: Gym Camera
      device_class: motion
      entity_id: camera.gym
      value_template: "{{ is_state('camera.gym', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_garage:
      friendly_name: Garage Camera
      device_class: motion
      entity_id: camera.garage
      value_template: "{{ is_state('camera.garage', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_driveway:
      friendly_name: Driveway Camera
      device_class: motion
      entity_id: camera.driveway
      value_template: "{{ is_state('camera.driveway', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_basement:
      friendly_name: Basement Camera
      device_class: motion
      entity_id: camera.basement
      value_template: "{{ is_state('camera.basement', 'motion') }}"
      delay_off:
        seconds: 30
