- platform: template
  sensors:
    motion_gym:
      friendly_name: Gym Camera
      device_class: motion
      value_template: "{{ is_state('camera.gym_fluent', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_garage:
      friendly_name: Garage Camera
      device_class: motion
      value_template: "{{ is_state('camera.garage_main_fluent', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_driveway:
      friendly_name: Driveway Camera
      device_class: motion
      value_template: "{{ is_state('camera.driveway_fluent', 'motion') }}"
      delay_off:
        seconds: 30
- platform: template
  sensors:
    motion_basement:
      friendly_name: Basement Camera
      device_class: motion
      value_template: "{{ is_state('camera.basement_storage_fluent', 'motion') }}"
      delay_off:
        seconds: 30
