language: python
python:
  - "3.6.4"
before_install:
  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml
install:
  - sudo apt-get install libudev-dev
  - pip3 install homeassistant-pyozw==0.1.3
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all