resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.4
    type: module

title: Home
views:
  - icon: mdi:music
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room        
        artwork: cover
        hide_power: true
        sonos_grouping:
          - entity_id: media_player.office
            name: Sonos Office
          - entity_id: media_player.master_bedroom
            name: Sonos Master bedroom
          - entity_id: media_player.dinning_room
            name: Sonos Dining room

  - icon: mdi:camera
    cards:
      - type: picture-glance
        title: Front Door
        entities:
          - binary_sensor.front_yard_camera_driveway_activity
          - binary_sensor.front_yard_camera_motion_detected
          - binary_sensor.front_yard_camera_online
          - binary_sensor.front_yard_camera_person_detected
          - binary_sensor.front_yard_camera_sound_detected
        camera_image: camera.front_yard
      - type: picture-glance
        title: Driveway
        entities:
          - binary_sensor.driveway_camera_driveway_activity
          - binary_sensor.driveway_camera_motion_detected
          - binary_sensor.driveway_camera_online
          - binary_sensor.driveway_camera_person_detected
          - binary_sensor.driveway_camera_sound_detected
        camera_image: camera.driveway
      - type: picture-glance
        title: Backyard
        entities:
          - binary_sensor.backyard_camera_driveway_activity
          - binary_sensor.backyard_camera_motion_detected
          - binary_sensor.backyard_camera_online
          - binary_sensor.backyard_camera_person_detected
          - binary_sensor.backyard_camera_sound_detected
        camera_image: camera.backyard
