resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.4
    type: module

title: Home
views:
  - icon: mdi:music
    cards:
      - type: horizontal-stack
        cards:
          - entity: media_player.office
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
          - entity: media_player.master_bedroom
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
      - type: horizontal-stack
        cards:
          - entity: media_player.dinning_room
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
          - entity: media_player.living_room   
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
          - entity: media_player.hannah
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
          - type: entities
            entities:
              - type: custom:mini-media-player
                entity: group.media_players
                group: true
                source: icon
                info: short
                hide:
                  volume: true
                  power: true
              - type: custom:mini-media-player
                entity: mmedia_player.dinning_room
                group: true
                hide:
                  controls: true
              - type: custom:mini-media-player
                entity: media_player.living_room
                group: true
                hide:
                  controls: true
              - type: custom:mini-media-player
                entity: media_player.office
                group: true
                hide:
                  controls: true
              - type: custom:mini-media-player
                entity: media_player.master_bedroom
                group: true
                hide:
                  controls: true
          
  - icon: mdi:camera
    cards:
      - type: picture-glance
        title: Front Door
        entities:
          - binary_sensor.front_yard_camera_front_door_activity
          - binary_sensor.front_yard_camera_motion_detected
          - binary_sensor.front_yard_camera_online
          - binary_sensor.front_yard_camera_person_detected
          - binary_sensor.front_yard_camera_sound_detected
        camera_image: camera.front_yard
      - type: picture-glance
        title: Driveway
        entities:
          - binary_sensor.driveway_camera_driveway_activity
          - binary_sensor.driveway_camera_motion_detected
          - binary_sensor.driveway_camera_online
          - binary_sensor.driveway_camera_person_detected
          - binary_sensor.driveway_camera_sound_detected
        camera_image: camera.driveway
      - type: picture-glance
        title: Backyard
        entities:
          - binary_sensor.backyard_camera_motion_detected
          - binary_sensor.backyard_camera_online
          - binary_sensor.backyard_camera_person_detected
          - binary_sensor.backyard_camera_sound_detected
        camera_image: camera.backyard
