resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.4
    type: module

title: Music
views:
  - badges: []
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room        
        artwork: cover
        hide_power: true
        sonos_grouping:
          - entity_id: media_player.office
            name: Sonos Office
          - entity_id: media_player.master_bedroom
            name: Sonos Master bedroom