title: Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.9.3
    type: module
  - url: /local/mini-media-player-bundle.js
    type: module
  - url: /local/simple-weather-card.bundle.js
    type: module
  - url: /local/simple-thermostat.js
    type: module
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
views:
  - path: default_view
    title: Home
    icon: 'mdi:home'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Room Location
            entities:
              #- sensor._room_status
              - sensor.michael_phone_battery
            state_image:
              "home": /local/images/michael_home.jpg
              "not_home": /local/images/michael_away.jpg
            aspect_ratio: 16:9
            entity: person.michael_lipscombe
          - type: picture-glance
            title: Room Location
            entities:
              #- sensor.hannah_room_status
              - sensor.hannah_phone_battery
            state_image:
              "home": /local/images/hannah_home.jpg
              "not_home": /local/images/hannah_away.jpg
            aspect_ratio: 16:9
            entity: person.hannah_lipscombe
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.espresso_machine
            name: Espresso
            icon: mdi:coffee
            tap_action:
              action: toggle
          - type: entity-button
            entity: lock.node_4
            name: Front
            tap_action:
              action: call-service
              service: lock.lock
              service_data:
                entity_id: lock.node_4
            hold_action:
              action: call-service
              service: lock.unlock
              service_data:
                entity_id: lock.node_4
          - type: entity-button
            entity: switch.hannah_heater
            name: Heater
            icon: mdi:radiator
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.in_wall_toggle_switch_120_277_qfsw_500s
            icon: mdi:lightbulb
            name: Garage Ext
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
            icon: mdi:lightbulb
            name: Front Patio
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.deck_wall_light_light
            name: Deck
            icon: mdi:lightbulb
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.plant_corner
            name: Plant Corner
            icon: mdi:lightbulb
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.sengled_e11_g13_light
            name: Music Corner
            icon: mdi:lightbulb
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - camera_image: camera.driveway_fluent
            entities:
              - binary_sensor.motion_driveway
            type: picture-glance
          - camera_image: camera.garage_main_fluent
            entities:
              - binary_sensor.motion_garage
            type: picture-glance
          - camera_image: camera.basement_storage_fluent
            entities:
              - binary_sensor.motion_basement
            type: picture-glance
          - camera_image: camera.gym_fluent
            entities:
              - binary_sensor.motion_gym
            type: picture-glance

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Sun Elevation
                entities:
                  - sensor.sun_elevation
                line_color: '#b58e31'
                line_width: 4
              - type: custom:mini-graph-card
                name: AdGuard Blocked
                entities:
                  - sensor.adguard_home_dns_queries_blocked_ratio
                line_color: '#e74c3c'
                line_width: 4
                icon: mdi:shield-check
      - type: horizontal-stack
        cards:
          - type: custom:simple-thermostat
            entity: climate.thermostat
            name: Thermostat
            step_size: 1
            sensors:
              - entity: sensor.thermostat_humidity
                name: Humidity
          - type: entities
            title: AdGuard Home
            icon: mdi:shield-check
            entities:
              - entity: switch.adguard_home_protection
                name: Protection
              - entity: switch.adguard_home_filtering
                name: Filtering
              - entity: sensor.adguard_home_dns_queries_blocked_ratio
                name: Block Rate
              
  - path: rachio
    title: Rachio
    icon: 'mdi:sprinkler-variant'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            title: Status
            entities:
              - entity: binary_sensor.rachio
                name: Connectivity
              - entity: binary_sensor.rachio_rain_sensor
                name: Rain Detected
              - entity: switch.rachio_in_standby_mode
                name: Standby Mode
              - entity: switch.rachio_rain_delay
                name: Rain Delay
          - type: entities
            title: Schedules
            entities:
              - entity: switch.lawn_schedule_2
                name: Lawn Schedule
              - entity: switch.trees_and_shrubs_drip_schedule
                name: Trees & Shrubs
              - entity: switch.vegetable_garden_schedule
                name: Vegetable Garden
      - type: horizontal-stack
        cards:
          - type: entities
            title: Front Yard
            entities:
              - entity: switch.front_yard
              - entity: switch.front_strip
              - entity: switch.front_yard_drip
          - type: entities
            title: Backyard
            entities:
              - entity: switch.backyard_south
              - entity: switch.backyard_west
              - entity: switch.backyard_east
              - entity: switch.backyard_inner
              - entity: switch.shrubs_and_trees_drip
