title: Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.9.3
    type: module
  - url: /local/mini-media-player-bundle.js
    type: module
  - url: /local/simple-weather-card.bundle.js
    type: module
  - url: /local/simple-thermostat.js
    type: module
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
views:
  - path: default_view
    title: Home
    icon: 'mdi:home'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Room Location
            entities:
              #- sensor._room_status
              - sensor.michael_phone_battery
            state_image:
              "home": /local/images/michael_home.jpg
              "not_home": /local/images/michael_away.jpg
            aspect_ratio: 16:9
            entity: person.michael_lipscombe
          - type: picture-glance
            title: Room Location
            entities:
              #- sensor.hannah_room_status
              - sensor.hannah_phone_battery
            state_image:
              "home": /local/images/hannah_home.jpg
              "not_home": /local/images/hannah_away.jpg
            aspect_ratio: 16:9
            entity: person.hannah_lipscombe
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: media_player.great_room
                state_not: "off"
            card:
              type: custom:mini-media-player
              entity: media_player.great_room
              icon: mdi:speaker-multiple
              artwork: cover
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.espresso_machine
            name: Espresso
            icon: mdi:coffee
            tap_action:
              action: toggle
          - type: entity-button
            entity: lock.schlage_connect_smart_deadbolt
            name: Front
            tap_action:
              action: call-service
              service: lock.lock
              service_data:
                entity_id: lock.schlage_connect_smart_deadbolt
            hold_action:
              action: call-service
              service: lock.unlock
              service_data:
                entity_id: lock.schlage_connect_smart_deadbolt
          - type: entity-button
            entity: switch.hannah_heater
            name: Heater
            icon: mdi:radiator
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.in_wall_toggle_switch_120_277_qfsw_500s
            icon: mdi:lightbulb
            name: Garage Ext
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s
            hold_action:
              action: call-service
              service: switch.turn_off
              service_data:
                entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s
          - type: entity-button
            entity: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
            icon: mdi:lightbulb
            name: Front Patio
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
            hold_action:
              action: call-service
              service: switch.turn_off
              service_data:
                entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
          - type: entity-button
            entity: switch.double_plug_2
            icon: mdi:lightbulb
            name: Hannah Reading
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.double_plug_2
            hold_action:
              action: call-service
              service: switch.turn_off
              service_data:
                entity_id: switch.double_plug_2
          - type: entity-button
            entity: switch.plug_in_1_outlet_switch_500s
            name: Lounge
            icon: mdi:lightbulb
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - camera_image: camera.driveway_fluent
            entities:
              - binary_sensor.motion_driveway
            type: picture-glance
          - camera_image: camera.garage_main_fluent
            entities:
              - binary_sensor.motion_garage
            type: picture-glance
          - camera_image: camera.basement_storage_fluent
            entities:
              - binary_sensor.motion_basement
            type: picture-glance
          - camera_image: camera.gym_fluent
            entities:
              - binary_sensor.motion_gym
            type: picture-glance

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Sun Elevation
                entities:
                  - sensor.sun_elevation
                line_color: '#b58e31'
                line_width: 4
              
  - path: greatroom
    title: Living Room
    icon: 'mdi:sofa'
    badges: []
    cards:
      - type: custom:mini-media-player
        entity: media_player.great_room
        icon: mdi:music
        artwork: cover

  - path: bedroom
    title: Bedroom
    icon: 'mdi:hotel'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - binary_sensor.motion_sensor_158d000237a64a
                  - binary_sensor.bathroom_motion
                  - sensor.bathroom_battery
      - type: custom:mini-media-player
        entity: media_player.master_bedroom
        icon: mdi:music
        artwork: cover
  - path: office
    title: Office
    icon: 'mdi:keyboard'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  # - binary_sensor.office_motion
                  # - sensor.office_battery
                  # - sensor.laptop_socket
      - type: custom:mini-media-player
        entity: media_player.office
        icon: mdi:music
        artwork: cover

  - path: auto
    title: Automations
    icon: 'mdi:creation'
    badges: []
    cards:
      - title: Home Automations
        type: entities
        entities:
          - automation.espresso_machine_on
          - automation.espresso_machine_off
          - automation.front_door_locked
          - automation.front_door_unlocked
        show_header_toggle: true
