resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.4
    type: module

title: Home
views:
  - icon: mdi:media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room        
        artwork: cover
        hide_power: true
        sonos_grouping:
          - entity_id: media_player.office
            name: Sonos Office
          - entity_id: media_player.master_bedroom
            name: Sonos Master bedroom
          - entity_id: media_player.dinning_room
            name: Sonos Dining room

  - icon: mdi:camera
    cards:
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_yard
      - type: picture-glance
        title: Driveway
        camera_image: camera.driveway
      - type: picture-glance
        title: Backyard
        camera_image: camera.backyard
