- platform: reolink_dev
  host: 192.168.2.41
  name: gym
  channel: 0
  username: admin
  password: !secret reolink_password
  stream: main
  protocol: rtsp
- platform: reolink_dev
  host: 192.168.2.41
  name: driveway
  channel: 1
  username: admin
  password: !secret reolink_password
  stream: main
  protocol: rtsp
