#####################################################################################
# Automation for when we're five minutes away
#####################################################################################

- alias: 'Automation five minutes away'
  trigger:
      platform: numeric_state
      entity_id: sensor.michael_to_home
      above: 5
      for: "00:01:00"
  condition:
      condition: and
      conditions:
          - condition: state
            entity_id: group.mobile_trackers
            state: "not_home"
          - condition: or
            conditions:
                - condition: state
                  entity_id: lock.none_current_lock_mode
                  state: "unlocked"
                - condition: state
                  entity_id: lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode
                  state: "unlocked"
  action:
    - service_template: "lock.lock"
      entity_id: lock.none_current_lock_mode
    - service_template: "lock.lock"
      entity_id: lock.touchscreen_deadbolt_z_wave_plus_current_lock_mode
    - service: notify.mobile_app_iphone
      data:
        title: "Home Assistant Alerts"
        message: "Detected you are more than five minutes from home, executing away automations"
        data:
          subtitle: "Away mode Automation"

#####################################################################################
# Automation for when we're more then an hour away
#####################################################################################
#####################################################################################
# Automation for when we're heading home after being an hour away
#####################################################################################

#####################################################################################
# Automation for when arriving home in vehicle
#####################################################################################

- alias: 'Automation arriving home in vehicle'
  trigger:
      - platform: state
        entity_id: group.mobile_trackers
        to: home
        from: not_home
  condition:
      - condition: and
        conditions:
            - condition: state
              entity_id: sensor.iphone_activity
              state: "Automotive"
            - condition: state
              entity_id: cover.garage_door
              state: "closed"
  action:
    - service_template: cover.open_cover
      entity_id: cover.garage_door
    - service: notify.mobile_app_iphone
      data:
        title: "Home Assistant Alerts"
        message: "Detected you arriving home, opening garage door"
        data:
          subtitle: "Away mode Automation"

#####################################################################################
# Automation for when leaving home in vehicle
#####################################################################################

- alias: 'Automation leaving home in vehicle'
  trigger:
      platform: numeric_state
      entity_id: sensor.michael_to_home
      above: 5
      for: "00:01:00"
  condition:
      - condition: and
        conditions:
            - condition: state
              entity_id: sensor.iphone_activity
              state: "Automotive"
            - condition: state
              entity_id: cover.garage_door
              state: "open"
  action:
    - service_template: cover.close_cover
      entity_id: cover.garage_door
    - service: notify.mobile_app_iphone
      data:
        title: "Home Assistant Alerts"
        message: "Detected you leaving home, closing garage door"
        data:
          subtitle: "Away mode Automation"
