#####################################################################################
###  Turn on the espresso machine at 5am and off at 3pm
#####################################################################################

- alias: 'Espresso Machine On'
  trigger:
    - platform: time
      at: '05:00:00'
  condition:
    - condition: state
      entity_id: group.mobile_trackers
      state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.espresso_machine
- alias: 'Espresso Machine Off'
  trigger:
    - platform: time
      at: '14:30:00'
  condition:
    - condition: state
      entity_id: switch.espresso_machine
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.espresso_machine
    - service: notify.alexa_media_kitchen_dot
      data:
        message: "The Espresso Machine was turned off"
        data:
          type: tts
- alias: 'Espresso Machine Off When Away'
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: state
      entity_id: group.mobile_trackers
      state: 'not_home'
      for:
        hours: 1
    - condition: state
      entity_id: switch.espresso_machine
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.espresso_machine
    - service: notify.mobile_app_iphone
      data:
        title: "Home Assistant Alerts"
        message: "Espresso Machine has been turned off as no one was home."
        data:
          subtitle: "Away"
