#####################################################################################
###  Turn on the espresso machine at 5am and off at 3pm
#####################################################################################

- alias: 'Espresso Machine On'
  trigger:
    - platform: time
      at: '05:00:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.mobile_trackers
          state: 'home'
  action:
    service_template: "switch.turn_on"
    entity_id: switch.espresso_machine
- alias: 'Espresso Machine Off'
  trigger:
    - platform: time
      at: '16:00:00'
  action:
    service_template: "switch.turn_off"
    entity_id: switch.espresso_machine
- alias: 'Espresso Machine Off When Away'
  trigger:
    - platform: time
      at: '9:00:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.mobile_trackers
          state: 'not_home'
          for:
            hours: 1
  action:
    - service_template: "switch.turn_off"
      entity_id: switch.espresso_machine
    - service: notify.michael_jeanie_iphones
      data:
        title: "Home Assistant Alerts"
        message: "Espresso Machine was turned off as no one is home."
        data:
          subtitle: "Away"

