#####################################################################################
###  Turn on the espresso machine at 5am and off at 3pm
#####################################################################################

- alias: 'Espresso Machine On'
  trigger:
    - platform: time
      at: '05:00:00'
  action:
    service_template: "switch.turn_on"
    entity_id: switch.espresso_machine
- alias: 'Espresso Machine Off'
  trigger:
    - platform: time
      at: '13:00:00'
  action:
    service_template: "switch.turn_off"
    entity_id: switch.espresso_machine