#####################################################################################
###  Lock Front Door at 9pm
#####################################################################################

- alias: 'Front Door Locked'
  trigger:
    - platform: time
      at: '21:00:00'
  action:
    - service_template: "lock.lock"
      entity_id: lock.schlage_allegion_unknown_type_0001_id_0468_locked
    - delay:
        seconds: 5
    - service: media_player.alexa_tts
      data:
        entity_id: 
          - media_player.michael_s_echo
        message: "The front door has been locked." 
    - service: notify.michael_jeanie_iphones
      data:
        title: "Smart Home Alerts"
        message: "The front door has been locked."
        data:
          subtitle: "Bed Time"
- alias: 'Front Door Unlocked'
  trigger:
  action:
    service_template: "lock.unlock"
    entity_id: lock.schlage_allegion_unknown_type_0001_id_0468_locked