#####################################################################################
###  Lock Front Door at 9pm
#####################################################################################

- alias: 'Front Door Locked'
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: time
      at: '23:00:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: lock.schlage_connect_smart_deadbolt
          state: unlocked
  action:
    - service_template: "lock.lock"
      entity_id: lock.schlage_connect_smart_deadbolt
    - delay:
        seconds: 5
    - service: notify.alexa_media_kitchen_dot
      data:
        message: "The front door was unlocked, I locked it."
        data:
          type: tts
    - service: notify.alexa_media_master_bedroom_dot
      data:
        message: "The front door was unlocked, I locked it."
        data:
          type: tts
    - service: notify.mobile_app_iphone_90
      data:
        title: "Home Assistant Alerts"
        message: "The front door has been locked."
        data:
          subtitle: "Bed Time"
- alias: 'Someone at Front Door'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  action:
    - service: notify.alexa_media_kitchen_dot
      data:
        message: "Someone is at the front door!"
        data:
          type: tts
    - service: notify.alexa_media_master_bedroom_dot
      data:
        message: "Someone is at the front door!"
        data:
          type: tts
