#####################################################################################
###  Close Garage Door at 9pm
#####################################################################################

- alias: 'Main Garage Door Closed'
  trigger:
    - platform: time
      at: '21:05:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: cover.garage_door_main
          state: open
  action:
    - service_template: "cover.close_cover"
      entity_id: cover.garage_door_main
    - delay:
        seconds: 5
    - service: notify.michael_jeanie_iphones
      data:
        title: "Smart Home Alerts"
        message: "The Main Garage Door has been closed."
        data:
          subtitle: "Bed Time"
    - service: media_player.alexa_tts
      data:
        entity_id:
          - media_player.alexa_media_kitchen_dot
        message: "The main garage door has been closed."
- alias: 'Small Garage Door Closed'
  trigger:
    - platform: time
      at: '21:08:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: cover.garage_door_small
          state: open
  action:
    - service_template: "cover.close_cover"
      entity_id: cover.garage_door_small
    - delay:
        seconds: 5
    - service: notify.michael_jeanie_iphones
      data:
        title: "Smart Home Alerts"
        message: "The Small Garage Door has been closed."
        data:
          subtitle: "Bed Time"
    - service: media_player.alexa_tts
      data:
        entity_id:
          - media_player.alexa_media_kitchen_dot
        message: "The small garage door has been closed."
