#####################################################################################
### Notify Hannah of nightly routines
#####################################################################################

- alias: 'Hannah bedtime, 10 minute warning'
  trigger:
    - platform: time
      at: '20:50:00'
  action:
    - service: media_player.alexa_tts
      data:
        entity_id:
          - media_player.michael_s_echo
        message: "ding dong! hey Hannah, 10 minutes until bedtime, please go brush your teeth."
- alias: 'Hannah bedtime'
  trigger:
    - platform: time
      at: '21:00:00'
  action:
    - service: media_player.alexa_tts
      data:
        entity_id:
          - media_player.michael_s_echo
        message: "ding dong! hey Hannah, it's bedtime."
- alias: 'Hannah Heater Off'
  trigger:
    - platform: time
      at: '05:00:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.mobile_trackers
          state: 'home'
  action:
    service_template: "switch.turn_off"
    entity_id: switch.hannah_heater
- alias: 'Espresso Machine On'
  trigger:
    - platform: time
      at: '16:00:00'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.mobile_trackers
          state: 'home'
  action:
    service_template: "switch.turn_on"
    entity_id: switch.hannah_heater
