#####################################################################################
###  Alert when washing machine has completed a cycle.
#####################################################################################
- alias: 'Washing machine has completed a load'
  trigger:
    - platform: state
      entity_id: sensor.washer_current_status
      to: 'end'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
  action:
    - service: notify.alexa_media_kitchen_dot
      data:
        message: "The washing machine has completed a load."
        data:
          type: tts
    - service: notify.alexa_media_master_bedroom_dot
      data:
        message: "The washing machine has completed a load."
        data:
          type: tts
#####################################################################################
###  Alert when dryer has completed a cycle.
#####################################################################################
- alias: 'Dryer has completed a load'
  trigger:
    - platform: state
      entity_id: sensor.dryer_current_status
      to: 'end'
  condition:
    condition: time
    after: '09:00:00'
    before: '22:00:00'
  action:
    - service: notify.alexa_media_kitchen_dot
      data:
        message: "The dryer has completed a load."
        data:
          type: tts
    - service: notify.alexa_media_master_bedroom_dot
      data:
        message: "The dryer has completed a load."
        data:
          type: tts
