#####################################################################################
###  Garage external lights
#####################################################################################
- alias: 'Garage External Lights On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service_template: "switch.turn_on"
      entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s
- alias: 'Garage External Lights Off'
  trigger:
    - platform: sun
      event: sunset
      offset: "03:00:00"
  action:
    - service_template: "switch.turn_off"
      entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s
#####################################################################################
###  Front Patio Lights
#####################################################################################
- alias: 'Front Patio Lights On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service_template: "switch.turn_on"
      entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
- alias: 'Front Patio Lights Off'
  trigger:
    - platform: sun
      event: sunset
      offset: "03:00:00"
  action:
    - service_template: "switch.turn_off"
      entity_id: switch.in_wall_toggle_switch_120_277_qfsw_500s_2
#####################################################################################
###  lounge lights
#####################################################################################
- alias: 'Lounge Lights On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.plug_in_1_outlet_switch_500s
    - service: light.turn_on
      entity_id: light.sengled_e11_g13_light
- alias: 'Lounge Lights Off'
  trigger:
    - platform: sun
      event: sunset
      offset: "05:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.plug_in_1_outlet_switch_500s
    - service: light.turn_off
      entity_id: light.sengled_e11_g13_light
#####################################################################################
###  deck light
#####################################################################################
- alias: 'Deck Wall Light On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      target:
        entity_id: light.deck_wall_light_light
- alias: 'Lounge Lights Off'
  trigger:
    - platform: sun
      event: sunset
      offset: "03:00:00"
  action:
    - service: light.turn_off
      target:
        entity_id: light.deck_wall_light_light