#####################################################################################
###  Garage external lights
#####################################################################################
- alias: 'Garage External Lights On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service_template: "switch.turn_on"
      entity_id: switch.in_wall_smart_toggle_switch_120_277vac_current_value
- alias: 'Garage External Lights Off'
  trigger:
    - platform: sun
      event: sunrise
      offset: "-05:00:00"
  action:
    - service_template: "switch.turn_off"
      entity_id: switch.in_wall_smart_toggle_switch_120_277vac_current_value
#####################################################################################
###  Front Patio Lights
#####################################################################################
- alias: 'Front Patio Lights On'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service_template: "switch.turn_on"
      entity_id: switch.in_wall_smart_toggle_switch_120_277vac_current_value_2
- alias: 'Front Patio Lights Off'
  trigger:
    - platform: sun
      event: sunrise
      offset: "-05:00:00"
  action:
    - service_template: "switch.turn_off"
      entity_id: switch.in_wall_smart_toggle_switch_120_277vac_current_value_2
