- alias: "Restart HA if WeMo switch isn't found after 15 minutes"
  trigger:
    platform: state
    entity_id: device_tracker.wemo
    from: 'not_home'
    to: 'home'
  condition:
    - condition: template
      value_template: '{% if states.switch.wemo %}false{% else %}true{% endif %}'
    - condition: state
      entity_id: script.restarthawemo
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.restarthawemo
- alias: 'Stop HA'
  trigger:
    - platform: state
      entity_id: switch.KillHass
      to: 'on'
  action:
    service: homeassistant.stop
- alias: 'Stop restarting HA is WeMo is found'
  trigger:
    platform: template
    value_template: '{% if states.switch.wemo %}true{% else %}false{% endif %}'
  condition:
    condition: state
    entity_id: script.restarthawemo
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: script.restarthawemo