- alias: 'Heating and Cooling set to away mode'
  trigger:
      platform: state
      entity_id: group.all_devices
      to: 'not_home'
  condition:
      condition: and
      conditions:
          - condition: state
            entity_id: sensor.jeanie_to_home_one_hour
            state: "true"
          - condition: state
            entity_id: sensor.michael_to_home_one_hour
            state: "true"
  action:
      service: climate.set_temperature
      entity_id: climate.thermostat
      data:
          away_mode: true
          away_cool_temperature: 82
          away_heat_temperature: 63
- alias: 'Heating and Cooling set to home mode'
  trigger:
      platform: state
      entity_id: group.all_devices
      to: 'home'
  action:
      service: climate.set_away_mode
      entity_id: climate.thermostat
      data:
        away_mode: false
